version: '3'

services:
  server:
    image: weather_server
    restart: always
    container_name: weatherserver
  client:
    image: weather_client
    restart: always
    ports:
    - "3000:80"
    container_name: weatherclient
